# This is a basic workflow to help you get started with Actions

name: manual_check

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mutation_testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      # Install deps
      - name: Install npm deps
        run: npm i

      # Run Stryker-Mutator check
      - name: Stryker-Mutator
        run: npm run test:mutate
